Repository the-deep/client, pull requests merged in 2019-02, with the labels that each got.

#683 Fix error while adding assessment from lead group
  src/views/EditAry/LeftPanel/index.js
Labels: bug

#682 Improve header styling of tabular book
  src/components/input/GeoInput/index.js
  src/components/other/TabularBook/Sheet/Header/index.js
  src/components/other/TabularBook/Sheet/Header/styles.scss
  src/views/Entries/FilterEntriesForm/styles.scss
Labels: ui

#693 Hotfix connector url 1.2.4
  package.json
  src/redux/reducers/domainData/projects.js
  src/rest/connectors.js
  src/rest/projects.js
  src/schema/projects.js
  src/views/Connector/Details/Form/index.js
  src/views/Connector/index.js
  src/views/Project/requests/ProjectOptionsGet.js
  yarn.lock
Labels: bug, hotfix

#696 Add missing createUrlForConnectorsOfProject
  src/rest/connectors.js
Labels: hotfix
